Repository kubernetes-sigs/kjob, pull requests merged in 2025-02, with the labels that each got.

#54 [Slurm] Fix error description on multiple parallel tasks with more than one step error.
  pkg/parser/slurm.go
  pkg/parser/slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/bug

#59 Add --pod-template-annotation and --pod-template-label flags
  apis/v1alpha1/application_profile_types.go
  config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  docs/commands/kjobctl_create/kjobctl_create_interactive.md
  docs/commands/kjobctl_create/kjobctl_create_job.md
  docs/commands/kjobctl_create/kjobctl_create_raycluster.md
  docs/commands/kjobctl_create/kjobctl_create_rayjob.md
  docs/commands/kjobctl_create/kjobctl_create_slurm.md
  pkg/builder/builder.go
  pkg/builder/builder_test.go
  pkg/builder/interactive_builder.go
  pkg/builder/interactive_builder_test.go
  pkg/builder/job_builder.go
  pkg/builder/job_builder_test.go
  pkg/builder/ray_cluster_builder_test.go
  pkg/builder/ray_job_builder_test.go
  pkg/builder/slurm_builder.go
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/printcrds/embed/manifest.gz
  pkg/testing/wrappers/job_wrappers.go
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature, release-note

#63 Fix GPU resources handling for slurm commands
  pkg/builder/slurm_builder.go
  pkg/cmd/create/create_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, kind/bug, release-note, size/S

#64 Bump sigs.k8s.io/controller-tools from 0.17.1 to 0.17.2 in /hack/tools
  config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  config/crd/bases/kjobctl.x-k8s.io_jobtemplates.yaml
  config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  config/samples/job-sample.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cmd/printcrds/embed/manifest.gz
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/cleanup, size/S
