Repository kubernetes-sigs/kjob, pull requests merged in 2025-01, with the labels that each got.

#31 Update the release process steps
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/cleanup, kind/documentation

#34 Update the installation docs with the new release version
  docs/installation.md
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/documentation

#41 Update descriptions.
  README.md
  docs/_index.md
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/documentation, size/S

#48 Set Logger for controller-runtime on integration test.
  go.mod
  go.sum
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/cleanup

#52 Stream logs from all the containers in a pod
  pkg/builder/slurm_builder.go
  pkg/cmd/create/create.go
  test/e2e/slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/bug
