Repository kubernetes-sigs/kjob, pull requests merged in 2025-03, with the labels that each got.

#67 Split unit tests for create command.
  pkg/cmd/create/create_interactive_test.go
  pkg/cmd/create/create_job_test.go
  pkg/cmd/create/create_raycluster_test.go
  pkg/cmd/create/create_rayjob_test.go
  pkg/cmd/create/create_slurm_test.go
  pkg/cmd/create/create_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, release-note-none, kind/cleanup

#69 [Slurm] Streaming logs from all containers.
  pkg/cmd/create/create.go
  test/e2e/slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/bug

#70 [Slurm] Stop streaming if Job was deleted.
  pkg/cmd/create/create.go
  test/e2e/slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/bug

#68 Add container-name flag
  docs/commands/kjobctl_create/kjobctl_create_slurm.md
  pkg/builder/builder.go
  pkg/builder/slurm_builder.go
  pkg/builder/slurm_builder_test.go
  pkg/cmd/create/create.go
  pkg/cmd/create/create_slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M, ok-to-test, kind/feature, release-note

#83 Dropping the use of Kueue's internal API
  go.mod
  go.sum
  pkg/cmd/describe/describe_printer.go
  pkg/util/util_test.go
  pkg/util/utils.go
  test/e2e/slurm_test.go
  test/framework/framework.go
  test/util/util.go
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note-none, ok-to-test, kind/cleanup

#85 Add missed Flag enum values
  apis/v1alpha1/application_profile_types.go
  config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  pkg/cmd/printcrds/embed/manifest.gz
  pkg/testing/wrappers/supported_mode_wrappers.go
Labels: cncf-cla: yes, lgtm, approved, kind/bug, release-note, size/S

#89 Move pkg/utils.go to pkg/maps/maps.go.
  pkg/cmd/describe/describe_printer.go
  pkg/util/maps/maps.go
  pkg/util/maps/maps_test.go
  pkg/util/validate/validate.go
  test/e2e/slurm_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/cleanup, size/S

#97 Add cherry_pick_pull.sh.
  hack/cherry_pick_pull.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note-none, kind/cleanup

#98 Bump go version to 1.24.1.
  go.mod
  hack/tools/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/cleanup

#99 Bump github.com/ray-project/kuberay/ray-operator from 1.2.2 to 1.3.1.
  config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  go.mod
  go.sum
  pkg/cmd/printcrds/embed/manifest.gz
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/cleanup, size/XL

#104 Update README.md after bump go version.
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/cleanup

#86 Optimize TestCreateSlurmCmd.
  pkg/cmd/create/create_slurm_test.go
  pkg/testing/wrappers/configmap_wrappers.go
  pkg/testing/wrappers/container_wrappers.go
  pkg/testing/wrappers/job_wrappers.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, release-note-none, kind/cleanup

#101 Add Test Coverage on README.md.
  README.md
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/documentation, size/S

#105 Use testing.TB.Context() instead of context.Background().
  pkg/builder/builder_test.go
  pkg/builder/interactive_builder_test.go
  pkg/builder/job_builder_test.go
  pkg/builder/ray_cluster_builder_test.go
  pkg/builder/ray_job_builder_test.go
  pkg/builder/slurm_builder_test.go
  pkg/cmd/create/create_interactive_test.go
  pkg/cmd/create/create_job_test.go
  pkg/cmd/create/create_raycluster_test.go
  pkg/cmd/create/create_rayjob_test.go
  pkg/cmd/create/create_slurm_test.go
  pkg/cmd/delete/delete_interactive_test.go
  pkg/cmd/delete/delete_job_test.go
  pkg/cmd/delete/delete_ray_cluster_test.go
  pkg/cmd/delete/delete_ray_job_test.go
  pkg/cmd/delete/delete_slurm_test.go
  test/e2e/suite_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, approved, release-note-none, size/M, kind/cleanup

#109 Automated cherry pick of #74: Bump sigs.k8s.io/kind from 0.26.0 to 0.27.0 in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#108 Align e2e-test.sh.
  hack/e2e-test.sh
Labels: cncf-cla: yes, lgtm, approved, release-note-none, kind/cleanup, size/S

#87 Optimize TestSlurmBuilderDo.
  pkg/builder/slurm_builder_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note-none, kind/cleanup

#111 Stop supporting k8s v1.29.
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/cleanup, kind/documentation

#114 Bump sigs.k8s.io/kueue from 0.11.1 to 0.11.2
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/cleanup
